### ISSUE TITLE
usage in 1903 versions of windows

### ISSUE THREAD

**Issue by krjan02** [SamuelTulach/efi-memory#2]
Hey, thanks for this great Project

I have been trying to port this to Windows 1903, to do so i have modified the hook function to work with `win32kfull.sys ->NtGdiGetCOPPCompatibleOPMInformation`. I have tested this in the orginal kdmapper before with success. Now with the efi driver, i get "ATTEMPTED WRITE TO READONLY MEMORY". That's most likely because the `win32kfull.sys ->NtGdiGetCOPPCompatibleOPMInformation` function is read/execute only. I have been looking at the gnuefi libary to find something like "ChangeProtection". 

Any ideas on this?

**Comment by SamuelTulach** [comment]
[I think this solves it.](https://github.com/SamuelTulach/efi-memory/commit/b216b24b8d90c7ce06af334506aa0814c8a492bb)

**Comment by ctrlone** [comment]
Hi, I got the same issue, I'm on 1903. It still does not map.

log:
[-] Failed to allocate remote image in kernel
[-] Failed to map kernelmode.sys
