### ISSUE TITLE
I get a blank screen when i load memory.efi

### ISSUE THREAD

**Issue by afulsamet** [SamuelTulach/efi-memory#4]
I do nothing extra and i follow your steps. I did not compile your project, i just use it from the [Releases](https://github.com/SamuelTulach/efi-memory/releases). I boot my USB Drive with FAT32 & EFI Shell. I select my usb drive from EFI Shell and load the memory.efi. As in your example video, the EFI driver is loading but with a blank screen.

Thats my USB Drive:

![fat32_usb_drive](https://user-images.githubusercontent.com/27636298/82367933-40327880-9a1d-11ea-9bb0-fda5d56d87a9.png)

Mainboard: Intel H81C
BIOS: American Megatrends Inc.
BIOS Version: 4.6.5

![bios_img](https://user-images.githubusercontent.com/27636298/82368121-8e477c00-9a1d-11ea-990b-85271efa1672.jpg)

I thought it might work because it was loaded even though i got a black screen and i tried but didn't work.

------

I made a video to help you understand what's going on more clearly.

[![blank_screen_vid](https://img.youtube.com/vi/12qDsOkGKYY/maxresdefault.jpg)](https://www.youtube.com/watch?v=12qDsOkGKYY)
https://www.youtube.com/watch?v=12qDsOkGKYY

**Comment by SamuelTulach** [comment]
Can you send output of `ver` command in EFI shell? It seems like it works correctly, but it does not return you to the EFI shell. Maybe try to play a bit with boot order?

**Comment by afulsamet** [comment]
Yes, sure.

![IMG_20200520_001737](https://user-images.githubusercontent.com/27636298/82379608-dc657b00-9a2f-11ea-8b4a-3d7e329a279d.jpg)

I also use [EDK2 efi shell](https://github.com/tianocore/edk2/releases) you suggested. `ShellBinPkg\UefiShell\X64\Shell.efi`

**P.S** I played with the boot order, but the result did not change.

**Comment by SamuelTulach** [comment]
Well you are on older UEFI version (I am on 2.7 for example) so you might try to search for a BIOS update or try to figure out what is different on the older UEFI standard.

**Comment by afulsamet** [comment]
Yes, I think it might be due to the older UEFI version. My mainboard (Intel H81C) does not have brand and model. So I think I will not be able to update the bios. But still thank you for all the help.
