### ISSUE TITLE
Example kernel driver

### ISSUE THREAD

**Issue by sitapea1337** [SamuelTulach/efi-memory#5]
Hello!

I see you're recommending using "blank.sys" driver - do you have source for that example driver?

If yes, care to share it?

Thanks!

**Comment by SamuelTulach** [comment]
Already deleted it but here is a quick write-up from memory how it can look like. Make sure you compile it with custom entry point set, security checks disabled and control flow guard disabled.
```
#include <ntddk.h>

NTSTATUS 
DriverEntry(
    _In_ PDRIVER_OBJECT     DriverObject, 
    _In_ PUNICODE_STRING    RegistryPath
)
{
    UNREFERENCED_PARAMETER(DriverObject);
    UNREFERENCED_PARAMETER(RegistryPath);

    DbgPrintEx(0, 0, "Hello from the other side\n");

    return STATUS_SUCCESS;
}
```

**Comment by sitapea1337** [comment]
Yeah, no... I've set custom entry "DriverEntry", disabled security checks and control flow guard.

Getting BSOD:
PAGE_FAULT_IN_NONPAGED_AREA


Do you have blank driver project to share with necessary options pre-configured?

**Comment by SamuelTulach** [comment]
Try to set target Windows version to Windows 7  (and change type from Universal to Desktop) in Driver settings.

**Comment by sitapea1337** [comment]
This seems to do the trick - thank you very much!

My own RPM/WPM driver doesn't yet work with this efimapper though, but that isn't the place for this conversation.
