### ISSUE TITLE
Windows restarting after loading driver

### ISSUE THREAD

**Issue by ENJATZ** [SamuelTulach/efi-memory#6]
Hello guys,

I am trying to get this driver to work. I am used the compiled version of **memory.efi** and I am booting from the USB as it says in the guide. I get the blue screen with text confirmation that the driver was loaded, but right after my pc restarts.

Do you guys have any suggestions?

**Comment by SamuelTulach** [comment]
For some reason it fails on [SetVirtualAddressMapEvent](https://github.com/SamuelTulach/efi-memory/blob/master/driver/main.c#L179). There is probably nothing else to do than debugging it (which would be real pain on real hw) or trying to compile your own version and trying to figure out what exactly is causing it.

**Comment by ENJATZ** [comment]
I will try to compile it and see the results. Thank you!

**Comment by SamuelTulach** [comment]
Reopen the issue if you have any new information.
