### ISSUE TITLE
Error with gnu-efi-libs

### ISSUE THREAD

**Issue by oumuamuax** [SamuelTulach/efi-memory#8]
Hi, I am trying to use this in linux subsystem on windows.
Ubuntu 20 LTS, I know the system but I don't recognize the commands that should be used to download the repositories, therefore it gives me an error called:
root@Taker:~# ls
efi-memory
root@Taker:~# cd efi-memory/
root@Taker:~/efi-memory# ls
README.md  assets  client  driver  update.sh
root@Taker:~/efi-memory# ls -a
.  ..  .git  .vscode  README.md  assets  client  driver  update.sh
root@Taker:~/efi-memory# cd driver/
root@Taker:~/efi-memory/driver# ls
LICENSE.txt  Makefile  main.c  main.o  memory.efi  memory.so
root@Taker:~/efi-memory/driver# make
objcopy -j .text -j .sdata -j .data -j .dynamic \
        -j .dynsym  -j .rel -j .rela -j .reloc \
        --target=efi-rtdrv-x86_64 memory.so memory.efi
make: objcopy: Command not found
make: *** [Makefile:37: memory.efi] Error 127
root@Taker:~/efi-memory/driver#.

- how do i install gnu-efi-libs bro?, where is the command in ubuntu 20 lts :P THX

![image](https://user-images.githubusercontent.com/19560107/85168307-77898480-b26a-11ea-888e-c7143b03621a.png)

**Comment by SamuelTulach** [comment]
> make: objcopy: Command not found

`sudo apt install binutils`

**Comment by oumuamuax** [comment]
```
root@Taker:~/efi-memory# cd driver/
root@Taker:~/efi-memory/driver# make
objcopy -j .text -j .sdata -j .data -j .dynamic \
        -j .dynsym  -j .rel -j .rela -j .reloc \
        --target=efi-rtdrv-x86_64 memory.so memory.efi
```

Has been completed or error? 

```
root@Taker:~/efi-memory/driver# make
make: Nothing to be done for 'all'.
```
