### ISSUE TITLE
Loader does not work

### ISSUE THREAD

**Issue by webinsh** [SamuelTulach/efi-memory#9]
When trying to inject memory.efi nothing happens. 
After entering "load memory.efi" only GitHub link appears, however, it states that it is successful. After typing exit, normal windows boot is happening, no blue confirmation screen was present.
Trying to use kd(efi)mapper fork - https://prnt.sc/usw92y
Trying to load EFI memory - https://imgur.com/a/iR4lION

**Comment by s0t7x** [comment]
Seems like starting the UEFI Runtime Driver while in UEFI is successful but when booting into windows its terminated with the BootServices.
Do you have secure boot activated? Which windows version are you booting?

**Comment by SamuelTulach** [comment]
Instead of typing exit you might want to try locating the Windows bootx64.efi and running it directly. Also as @s0t7x said check secure boot.

**Comment by webinsh** [comment]
Thank you for the replies, however, it didn't help much
@s0t7x Secure boot is disabled. Windows version - 1909 build 18363.1139 - https://prnt.sc/v10wmr
@SamuelTulach  After searching through google, I couldn't find any information on where the windows boot EFI file is located. Only saw it in windows installation media

**Comment by SamuelTulach** [comment]
Just a stupid question, but are you even using EFI boot? If you are, you should be able to find in on one of the partitions (FS0 - FSx) in `EFI\Boot\bootx64.efi`.

**Comment by webinsh** [comment]
Well.. After searching through FS systems in EFI shell I was not able to find an EFI folder

**Comment by SamuelTulach** [comment]
![efi-enabled](https://user-images.githubusercontent.com/16323119/96376400-0659cf80-117f-11eb-9f93-ab64757ef24a.png)

Please check that you have EFI system install. If not than it will obviously not work...

**Comment by webinsh** [comment]
Well... Apparently, it is on Legacy. Is there any way to change it to UEFI https://prnt.sc/v223iy without reinstalling windows?

**Comment by SamuelTulach** [comment]
> 
> 
> Well... Apparently, it is on Legacy. Is there any way to change it to UEFI https://prnt.sc/v223iy without reinstalling windows?

*slow clap*

[How to switch from legacy mode to UEFI](http://letmegooglethat.com/?q=windows+switch+from+legacy+to+uefi)
